export const Product = [
  {
    id: "0",
    name: "Playstation 5",
    brand: "Sony",
    price: 4000,
    image: "app00.jpg",
    filter: "videogames",
  },
  {
    id: "1",
    name: "Xbox Series S",
    brand: "Xbox",
    price: 2500,
    image: "app01.jpg",
    filter: "videogames",
  },
  {
    id: "2",
    name: "Nintendo Switch",
    brand: "Nintendo",
    price: 2350,
    image: "app02.jpg",
    filter: "videogames",
  },
  {
    id: "3",
    name: "PC Gamer",
    brand: "Pichau",
    price: 6000,
    image: "app03.jpg",
    filter: "videogames",
  },
  {
    id: "4",
    name: "Playstation 4",
    brand: "Sony",
    price: 3200,
    image: "app04.jpg",
    filter: "videogames",
  },
  {
    id: "5",
    name: "Xbox One",
    brand: "Xbox",
    price: 2500,
    image: "app05.jpg",
    filter: "videogames",
  },
  {
    id: "6",
    name: "Playstation 2",
    brand: "Sony",
    price: 300,
    image: "app06.jpg",
    filter: "videogames",
  },
  {
    id: "7",
    name: "Playstation 3",
    brand: "Sony",
    price: 1200,
    image: "app07.jpg",
    filter: "videogames",
  },
  {
    id: "8",
    name: "Xbox 360",
    brand: "Xbox",
    price: 1100,
    image: "app08.jpg",
    filter: "videogames",
  },
  {
    id: "9",
    name: "Notebook HP SSD 500GB 6GB RAM",
    brand: "HP",
    price: 1950,
    image: "app09.jpg",
    filter: "notebooks",
  },
  {
    id: "10",
    name: "Notebook Asus HD 1TB 6GB RAM",
    brand: "Asus",
    price: 2200,
    image: "app10.jpg",
    filter: "notebooks",
  },
  {
    id: "11",
    name: "Notebook Accer HD 500GB 4GB RAM",
    brand: "Accer",
    price: 1650,
    image: "app11.jpg",
    filter: "notebooks",
  },
  {
    id: "12",
    name: "Notebook Samsung HD 500GB 8GB RAM",
    brand: "Xbox",
    price: 1780,
    image: "app12.jpg",
    filter: "notebooks",
  },
  {
    id: "13",
    name: "SmartTV LG UHD 60",
    brand: "LG",
    price: 3200,
    image: "app13.jpg",
    filter: "tvs",
  },
  {
    id: "14",
    name: "SmartTV Samsung 60",
    brand: "Samsung",
    price: 2999,
    image: "app14.jpg",
    filter: "tvs",
  },
  {
    id: "15",
    name: "SmarTV Samsung 40",
    brand: "Samsung",
    price: 1980,
    image: "app15.jpg",
    filter: "tvs",
  },
  {
    id: "16",
    name: "SmarTV Philips 80",
    brand: "Philips",
    price: 4789,
    image: "app16.jpg",
    filter: "tvs",
  },
  {
    id: "17",
    name: "SmarTV Samsung 55",
    brand: "Samsung",
    price: 2690,
    image: "app17.jpg",
    filter: "tvs",
  },
  {
    id: "18",
    name: "Iphone 11Pro",
    brand: "Apple",
    price: 4500,
    image: "app18.jpg",
    filter: "smartphones",
  },
  {
    id: "19",
    name: "Iphone 12Pro",
    brand: "Apple",
    price: 5200,
    image: "app19.jpg",
    filter: "smartphones",
  },
  {
    id: "20",
    name: "Iphone 12Pro Max",
    brand: "Iphone",
    price: 5600,
    image: "app20.jpg",
    filter: "smartphones",
  },
  {
    id: "21",
    name: "Xiaomi Redmi Note 12",
    brand: "Xiaomi",
    price: 2300,
    image: "app21.jpg",
    filter: "smartphones",
  },
  {
    id: "22",
    name: "Xiaomi Redmi Mi 10T",
    brand: "Xiomi",
    price: 1100,
    image: "app22.jpg",
    filter: "smartphones",
  },
  {
    id: "23",
    name: "Samsung Galaxy S23 Ultra",
    brand: "Samsung",
    price: 3200,
    image: "app23.jpg",
    filter: "smartphones",
  },
];

export function saveLocalStorage(key, information) {
  localStorage.setItem(key, JSON.stringify(information));
}

export function readLocalStorage(key) {
  return JSON.parse(localStorage.getItem(key));
}
